---
title: "Ocean pH"
author: "your name"
date: "the date"
format: html
editor: visual
---

A consequence of the increase in the atmospheric concentration of carbon dioxide (CO2) that has occurred over the last 250 years is that the oceans are absorbing more CO2 and as a consequence, becoming more acidic

You have been supplied with a data set taken from a figure published by the IPCC, which shows ocean pH vs time for the last 40 years or so.

The data are in the file `ipcc_AR6_WGI_Figure_5_20-pH.csv`. Note 

Your task is to write a script that uses the exact same sequence of steps as was used to analyse plant growth rate to determine whether there is evidence for any linear decline in pH over this perid, and , if so, what the rate of decline is: by how much does ocean pH change each year?

Once you have finished your analysis, report your conclusions in pain English.

You can use the plant growth rate script as a guide, and also the session notes. Note that the data in the csv file do not begin until line 6. Prior to that there is some meta data that tells you where the data comes from.